#!/usr/bin/env python3
"""Sprint 7I: interactive setup wizard for first-time users.

Asks the user a few questions, writes ``.env``, and runs a smoke test.
Designed for beginners who have never edited a dotenv file.

Usage:
    python setup_wizard.py
"""

from __future__ import annotations

import os
import sys

_REPO = os.path.dirname(os.path.abspath(__file__))
_ENV_PATH = os.path.join(_REPO, ".env")


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"  {prompt}{suffix}: ").strip()
    return val or default


def main() -> int:
    print("\n" + "=" * 56)
    print("  Algo Trader — Setup Wizard")
    print("=" * 56 + "\n")

    if os.path.exists(_ENV_PATH):
        print(f"  .env already exists at {_ENV_PATH}")
        overwrite = _ask("Overwrite? (y/N)", "N")
        if overwrite.lower() != "y":
            print("  Keeping existing .env. Done.")
            return 0

    print("\n  Step 1: Alpaca API credentials")
    print("  (get these from https://app.alpaca.markets/paper/dashboard/overview)\n")
    api_key = _ask("ALPACA_API_KEY")
    secret = _ask("ALPACA_SECRET_KEY")
    if not api_key or not secret:
        print("\n  ERROR: Both API key and secret are required.")
        return 1

    print("\n  Step 2: Account profile")
    print("  Beginner ($500-$2K) — conservative defaults, max safety")
    print("  Hobbyist ($2K-$10K)  — moderate risk, more strategies")
    print("  Learner  ($10K+)    — full features, advanced dashboard")
    profile = _ask("Profile (beginner/hobbyist/learner)", "beginner")
    if profile not in ("beginner", "hobbyist", "learner"):
        profile = "beginner"

    print("\n  Step 3: Trading mode")
    mode = _ask("Mode (paper/live)", "paper")
    if mode not in ("paper", "live"):
        mode = "paper"

    # Build .env
    lines = [
        f"# Generated by setup_wizard.py",
        f"ALPACA_API_KEY={api_key}",
        f"ALPACA_SECRET_KEY={secret}",
        f"TRADING_MODE={mode}",
        f"USER_PROFILE={profile}",
        "",
        "# Feature flags (safe defaults)",
        "ATR_STOPS_ENABLED=true",
        "STATE_PERSISTENCE_ENABLED=true",
        "VOLATILITY_SIZING_ENABLED=true",
        "SENTIMENT_ENABLED=false",
        "LLM_ANALYST_ENABLED=false",
        "RL_STRATEGY_ENABLED=false",
        "DRIFT_DETECTION_ENABLED=true",
        "PARALLEL_FETCH_ENABLED=true",
        "",
        "# Monitoring (optional)",
        "# SENTRY_DSN=",
        "# METRICS_ENABLED=true",
        "# STRUCTURED_LOG=true",
    ]
    with open(_ENV_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\n  Wrote {_ENV_PATH}")

    # Smoke test
    print("\n  Running smoke test...")
    try:
        sys.path.insert(0, _REPO)
        from config import Config
        print(f"  Config loaded — profile: {profile}, mode: {Config.TRADING_MODE}")
        print(f"  Symbols: {Config.SYMBOLS[:3]}...")
    except Exception as e:
        print(f"  WARNING: Config import failed: {e}")
        print("  (This is OK if dependencies aren't installed yet.)")

    print("\n  Setup complete! Next steps:")
    print("    pip install -r requirements.txt")
    print("    python -m pytest tests/ -x -q  # run the test suite")
    print("    ./bot.sh start                  # start trading")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
