"""GICS sector definitions with top companies per sector.

Each sector maps to a list of tickers (up to ~100) drawn from
S&P 500, NASDAQ-100, and other large-cap indices.
TradingView exchange prefix defaults to NASDAQ or NYSE.
"""

SECTORS = {
    "technology": {
        "name": "Information Technology",
        "description": "Semiconductors, software, hardware, IT services, cloud computing",
        "tickers": [
            "AAPL", "MSFT", "NVDA", "AVGO", "ORCL", "CRM", "AMD", "ADBE", "CSCO", "ACN",
            "INTC", "TXN", "QCOM", "IBM", "INTU", "AMAT", "NOW", "ADI", "LRCX", "MU",
            "KLAC", "SNPS", "CDNS", "MRVL", "FTNT", "PANW", "CRWD", "MSI", "ROP", "NXPI",
            "APH", "FICO", "ADSK", "PLTR", "MCHP", "TEL", "ON", "HPQ", "MPWR", "ANSS",
            "KEYS", "CDW", "TYL", "ZBRA", "EPAM", "PAYC", "GEN", "JNPR", "TER", "SWKS",
            "AKAM", "FFIV", "NTAP", "WDC", "STX", "HPE", "DELL", "GDDY", "SMCI", "ARM",
            "SHOP", "NET", "DDOG", "SNOW", "ZS", "MDB", "TEAM", "HUBS", "VEEV", "WDAY",
            "TTD", "COIN", "ANET", "ESTC", "CFLT", "PATH", "S", "OKTA", "CRSP", "FIVN",
            "DBX", "DOCN", "APP", "IOT", "BILL", "GTLB", "APPF", "DT", "TENB", "RPD",
            "TOST", "MNDY", "SAMSARA", "GFS", "WOLF", "ACLS", "RMBS", "CRUS", "SITM", "POWI",
        ],
    },
    "healthcare": {
        "name": "Healthcare",
        "description": "Pharma, biotech, medical devices, managed care, life sciences",
        "tickers": [
            "UNH", "LLY", "JNJ", "ABBV", "MRK", "TMO", "ABT", "DHR", "PFE", "AMGN",
            "ELV", "SYK", "MDT", "ISRG", "BMY", "GILD", "VRTX", "CI", "BSX", "REGN",
            "ZTS", "BDX", "HCA", "MCK", "EW", "IDXX", "A", "IQV", "MTD", "RMD",
            "DXCM", "ALGN", "HOLX", "BAX", "CNC", "MOH", "BIIB", "ILMN", "WST", "WAT",
            "PODD", "TECH", "STE", "INCY", "MRNA", "JAZZ", "NBIX", "EXAS", "ALNY", "RARE",
            "SGEN", "PCVX", "IONS", "SRPT", "ARGX", "BMRN", "UTHR", "HALO", "INSM", "CORT",
            "MEDP", "RVMD", "TNDM", "NVCR", "TWIST", "LEGN", "RXRX", "CRNX", "KRYS", "VERA",
            "CRL", "ICLR", "VEEV", "TFX", "PEN", "MMSI", "NVST", "XRAY", "COO", "LNTH",
            "GKOS", "NTRA", "CERT", "IRTC", "TGTX", "PCTY", "DGX", "LH", "CAH", "ABC",
            "CVS", "HUM", "COR", "GEHC", "SOLV", "OGN", "VTRS", "TAK", "NVS", "AZN",
        ],
    },
    "financials": {
        "name": "Financial Services",
        "description": "Banks, insurance, capital markets, fintech, asset management",
        "tickers": [
            "BRK.B", "JPM", "V", "MA", "BAC", "WFC", "GS", "MS", "SPGI", "AXP",
            "BLK", "C", "SCHW", "CB", "PGR", "MMC", "ICE", "AON", "CME", "MCO",
            "MET", "AIG", "TRV", "PNC", "USB", "AJG", "AFL", "TFC", "BK", "PRU",
            "STT", "ALL", "FITB", "HBAN", "RF", "CFG", "CINF", "WRB", "RJF", "NTRS",
            "KEY", "ZION", "CMA", "FHN", "EWBC", "FNB", "SBNY", "WAL", "OZK", "PACW",
            "SOFI", "PYPL", "SQ", "AFRM", "UPST", "LC", "NU", "HOOD", "LPLA", "IBKR",
            "MKTX", "CBOE", "NDAQ", "FIS", "FISV", "GPN", "FLT", "WEX", "SSNC", "MSCI",
            "VRSN", "BR", "FDS", "TROW", "BEN", "IVZ", "AMG", "EV", "APAM", "VCTR",
            "ALLY", "DFS", "SYF", "COF", "MTB", "HBAN", "BOKF", "SNV", "ONB", "WTFC",
            "PNFP", "HWC", "SSB", "UBSI", "ABCB", "CADE", "HOPE", "GBCI", "FNB", "AX",
        ],
    },
    "consumer_discretionary": {
        "name": "Consumer Discretionary",
        "description": "Retail, autos, apparel, restaurants, travel, entertainment",
        "tickers": [
            "AMZN", "TSLA", "HD", "MCD", "NKE", "LOW", "BKNG", "SBUX", "TJX", "CMG",
            "ORLY", "MAR", "AZO", "HLT", "GM", "F", "ROST", "DHI", "LEN", "YUM",
            "ABNB", "LULU", "DKNG", "DASH", "EBAY", "RCL", "CCL", "NCLH", "EXPE", "DRI",
            "GPC", "LKQ", "PHM", "NVR", "TOL", "KBH", "MTH", "MDC", "GRMN", "POOL",
            "ULTA", "BBY", "DG", "DLTR", "FIVE", "W", "ETSY", "CHWY", "CVNA", "CARG",
            "RIVN", "LCID", "VFS", "LYFT", "UBER", "GRAB", "CPNG", "MELI", "SE", "JD",
            "PDD", "BABA", "NTES", "PVH", "TPR", "RL", "CPRI", "HBI", "GIII", "CROX",
            "DECK", "ON", "SKECHERS", "BIRD", "WYNN", "LVS", "MGM", "CZR", "PENN", "BYD",
            "PLAY", "EAT", "TXRH", "CAKE", "WING", "SHAK", "CAVA", "BROS", "DPZ", "QSR",
            "WEN", "JACK", "DINE", "ARCO", "LOCO", "TACO", "FWRG", "PZZA", "BJRI", "RUTH",
        ],
    },
    "consumer_staples": {
        "name": "Consumer Staples",
        "description": "Food, beverages, household products, tobacco, personal care",
        "tickers": [
            "PG", "KO", "PEP", "COST", "WMT", "PM", "MO", "MDLZ", "CL", "EL",
            "STZ", "GIS", "KMB", "SYY", "HSY", "KDP", "MKC", "HRL", "CPB", "SJM",
            "K", "TSN", "CAG", "BG", "ADM", "INGR", "DAR", "FLO", "LNDC", "JJSF",
            "LANC", "THS", "BGS", "HAIN", "FRPT", "CENT", "UVV", "VGR", "BTI", "BUD",
            "TAP", "SAM", "MNST", "CELH", "FIZZ", "COKE", "KOF", "DEO", "BF.B", "STZ",
            "CHD", "CLX", "SPB", "HNST", "EPC", "ENR", "IPAR", "COTY", "KVUE", "WBA",
            "KR", "ACI", "SFM", "GO", "IMKTA", "NGVC", "VLGEA", "CHEF", "USFD", "PFGC",
            "UNFI", "SPTN", "ANDE", "CALM", "VITL", "SMPL", "BYND", "OTLY", "TTCF", "STKL",
            "NUS", "HELE", "REV", "EDGW", "PRGO", "BRBR", "CELH", "COCO", "ZVIA", "WDDD",
            "WW", "HIMS", "OLPX", "SKIN", "LFMD", "MRUS", "EARS", "RVLV", "CURV", "ACI",
        ],
    },
    "energy": {
        "name": "Energy",
        "description": "Oil & gas exploration, refining, equipment, services, renewables",
        "tickers": [
            "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PXD", "PSX", "VLO", "OXY",
            "WMB", "HES", "DVN", "HAL", "KMI", "BKR", "FANG", "TRGP", "OKE", "CTRA",
            "MRO", "APA", "EQT", "AR", "RRC", "SWN", "CHK", "PR", "MTDR", "SM",
            "CHRD", "MGY", "NOV", "FTI", "WHD", "LBRT", "PTEN", "HP", "RIG", "DO",
            "VAL", "NE", "BORR", "SDRL", "TDW", "OII", "CLB", "WTTR", "PUMP", "ARIS",
            "DK", "PBF", "DINO", "CVI", "PARR", "HFC", "CLMT", "CAPL", "LPG", "FLNG",
            "DTM", "HESM", "ENLC", "WES", "PAA", "ET", "EPD", "MPLX", "CEQP", "USAC",
            "AM", "CWEN", "NEP", "BEPC", "AES", "ORA", "NOVA", "RUN", "ENPH", "SEDG",
            "FSLR", "CSIQ", "JKS", "ARRY", "MAXN", "SHLS", "STEM", "BLDP", "PLUG", "BE",
            "CLNE", "NEXT", "AMPS", "EVGO", "CHPT", "BLNK", "DCFC", "LEU", "SMR", "NNE",
        ],
    },
    "industrials": {
        "name": "Industrials",
        "description": "Aerospace, defense, machinery, construction, transportation, logistics",
        "tickers": [
            "GE", "CAT", "UNP", "HON", "RTX", "UPS", "BA", "LMT", "DE", "ETN",
            "GD", "NOC", "ITW", "WM", "EMR", "CSX", "NSC", "FDX", "MMM", "PH",
            "TT", "CARR", "CTAS", "ROK", "FAST", "ODFL", "RSG", "AME", "DOV", "XYL",
            "GWW", "PCAR", "SWK", "IR", "WAB", "J", "PWR", "LII", "GNRC", "HWM",
            "TXT", "LDOS", "BAH", "SAIC", "CACI", "KBR", "DRS", "HII", "LHX", "AXON",
            "VRSK", "BR", "FTV", "NDSN", "AOS", "RBC", "CMI", "AGCO", "OSK", "TTC",
            "MLM", "VMC", "BLDR", "MAS", "JCI", "OC", "LECO", "ALLE", "AYI", "GGG",
            "WCC", "EFX", "IEX", "CW", "HEI", "TDY", "BWXT", "SPR", "ERJ", "RKLB",
            "ASTS", "RDW", "LUNR", "MNTS", "ASTR", "SPCE", "JOBY", "LILM", "ACHR", "BLDE",
            "DAL", "UAL", "LUV", "AAL", "ALK", "JBLU", "SAVE", "HA", "SKYW", "MESA",
        ],
    },
    "materials": {
        "name": "Materials",
        "description": "Chemicals, metals, mining, paper, containers, construction materials",
        "tickers": [
            "LIN", "APD", "SHW", "ECL", "FCX", "NEM", "NUE", "DOW", "DD", "PPG",
            "VMC", "MLM", "CE", "ALB", "IFF", "EMN", "AVY", "PKG", "IP", "WRK",
            "BALL", "SEE", "SON", "BMS", "GPK", "CLF", "STLD", "RS", "CMC", "ATI",
            "HCC", "ARCH", "ARLP", "BTU", "CEIX", "CHNR", "X", "AA", "CENX", "KALU",
            "MEOH", "OLN", "TROX", "KRO", "VNTR", "IOSP", "CC", "AXTA", "RPM", "GRA",
            "FUL", "CBT", "KWR", "HWKN", "HUN", "WLK", "LYB", "DSEY", "TSE", "ASIX",
            "RIO", "BHP", "VALE", "SCCO", "TECK", "HBM", "PAAS", "AG", "CDE", "EXK",
            "HL", "FSM", "MAG", "SSRM", "KGC", "AEM", "GOLD", "WPM", "FNV", "RGLD",
            "AUY", "IAG", "EDV", "SILV", "SVM", "GPL", "USAS", "MUX", "BTG", "OR",
            "CSTM", "HAYN", "MTRN", "ZEUS", "SXC", "ITE", "UUUU", "CCJ", "DNN", "URG",
        ],
    },
    "real_estate": {
        "name": "Real Estate",
        "description": "REITs — data centers, towers, industrial, residential, retail, office",
        "tickers": [
            "PLD", "AMT", "EQIX", "CCI", "PSA", "SPG", "O", "WELL", "DLR", "VICI",
            "AVB", "EQR", "SBAC", "WPC", "ARE", "VTR", "IRM", "CBRE", "MAA", "ESS",
            "UDR", "CPT", "INVH", "AMH", "ELS", "SUI", "REXR", "FR", "STAG", "TRNO",
            "EGP", "PLD", "COLD", "DRE", "REG", "FRT", "KIM", "BRX", "SITC", "AKR",
            "NNN", "STORE", "ADC", "EPRT", "GTY", "SRC", "FCPT", "PINE", "PLYM", "IIPR",
            "CUBE", "EXR", "LSI", "NSA", "REXR", "AIRC", "NLY", "AGNC", "STWD", "BXMT",
            "LADR", "ARI", "KREF", "BRSP", "RC", "AOMR", "PMT", "RITM", "TWO", "CIM",
            "MPW", "OHI", "SBRA", "HR", "DOC", "PEAK", "CTRE", "LTC", "NHI", "UHT",
            "BXP", "SLG", "VNO", "KRC", "HIW", "JBGS", "CUZ", "OFC", "PDM", "DEI",
            "ALEX", "IRT", "NXRT", "ELME", "APTS", "VRE", "GMRE", "GNL", "GLPI", "RHP",
        ],
    },
    "utilities": {
        "name": "Utilities",
        "description": "Electric, gas, water utilities, renewable energy generators, nuclear",
        "tickers": [
            "NEE", "SO", "DUK", "D", "SRE", "AEP", "EXC", "XEL", "WEC", "ED",
            "PCG", "PEG", "EIX", "AWK", "DTE", "ES", "FE", "AEE", "ETR", "CMS",
            "LNT", "EVRG", "ATO", "NI", "PNW", "OGE", "BKH", "AVA", "NWE", "POR",
            "IDA", "MDU", "SWX", "SR", "NJR", "SJI", "CPK", "UTL", "OTTR", "MSEX",
            "YORW", "CWCO", "SJW", "WTR", "CWT", "WTRG", "AWR", "ARIS", "ARTNA", "CTWS",
            "VST", "CEG", "NRG", "OGE", "TAL", "CWEN", "AQN", "BEP", "NEP", "RNW",
            "AES", "ENPH", "SEDG", "FSLR", "RUN", "NOVA", "ARRY", "MAXN", "CSIQ", "JKS",
            "NNE", "SMR", "OKLO", "CCJ", "LEU", "UUUU", "DNN", "UEC", "URG", "NXE",
            "PLUG", "BE", "BLDP", "FCEL", "CLNE", "STEM", "SHLS", "CHPT", "BLNK", "EVGO",
            "NFE", "TELL", "LNG", "GLNG", "FLNG", "CQP", "KMI", "WMB", "OKE", "TRGP",
        ],
    },
    "communication_services": {
        "name": "Communication Services",
        "description": "Media, entertainment, telecom, social media, streaming, gaming",
        "tickers": [
            "META", "GOOGL", "NFLX", "DIS", "CMCSA", "T", "VZ", "TMUS", "CHTR", "EA",
            "ATVI", "WBD", "PARA", "FOX", "FOXA", "NWSA", "NWS", "LYV", "MTCH", "PINS",
            "SNAP", "RBLX", "SPOT", "ROKU", "ZM", "TWLO", "U", "TTWO", "SIRI", "LUMN",
            "IRDM", "GSAT", "TSAT", "SATS", "DISH", "CABO", "CNSL", "USM", "LBRDA", "LBRDK",
            "WMG", "UMG", "MSGS", "MSGE", "VLCN", "GRVY", "ZNGA", "GLBE", "ANGI", "IAC",
            "YELP", "CARG", "CARS", "ZG", "RDFN", "OPEN", "TRLY", "PUBM", "MGNI", "DSP",
            "IAS", "DV", "CRTO", "TBLA", "TTD", "APPS", "DLO", "BRZE", "AMPL", "BMBL",
            "SKLZ", "SOFI", "FUBO", "BATRA", "BATRK", "EDR", "TKO", "WWE", "DKNG", "RSI",
            "PENN", "FLUT", "GAMB", "CHDN", "BALY", "GAN", "AGS", "ACEL", "GENI", "SRAD",
            "CTV", "IHRT", "CMLS", "ETM", "SALM", "CCO", "LAMR", "OUT", "MGID", "COMP",
        ],
    },
}

# Flat list of all sectors
SECTOR_NAMES = list(SECTORS.keys())
